import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import {
  PlusIcon,
  SearchIcon,
  DropIcon,
  EditIcon,
  DeleteIcon,
  CopyIcon,
  EmailIcon,
  PreviousIcon,
  NextIcon,
  NotificationIcon,
  FilterIcon,
  DashboardIcon,
  ProductIcon,
  MoreIcon,
} from "@/components/Icon";
import { BiChevronDown } from "react-icons/bi";
import Image from "next/image";
import Curology from "/public/assests/skincare.png";
import Xbox from "/public/assests/xboxseries.png";
import Smartwatch from "/public/assests/smartwatch.png";
import Vans from "/public/assests/vans classic.png";
import Xboxseries from "/public/assests/xboxseriescontroller.png";
import Ipad from "/public/assests/ipadpro.png";
import Lovecorn from "/public/assests/lovecorn.png";
import Logittex from "/public/assests/logitex.png";
import Chair from "/public/assests/tallchair.png";
import Leather from "/public/assests/leatherjacket.png";
import Vector1 from "/public/assests/Vector 18.svg";
import Vector3 from "/public/assests/Vector 16.svg";
import Vector4 from "/public/assests/Vector 17.svg";
import Vector9 from "/public/assests/Vector 19.svg";

export default function Home() {
  function toggleDropdown() {
    setIsOpen(!isOpen);
  }
  const [isOpen, setIsOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Kitagrow</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="mt-4 w-full ">
        <div className="border-t hidden md:block  border-l border-none shadow-md rounded-[40px_0_0_0] min-h-[1032px] ">
          <div className="p-6">
            <h1 className="text-[32px] font-bold">Product List</h1>
            <p className="text-[16px] text-[#667085]">
              Manage & Add Product list on your marketplace
            </p>
            <div className="flex mt-8 w-auto justify-between">
              <div className="flex gap-2">
                <Link
                  href="/newproduct"
                  className="flex items-center bg-[#443DF6] rounded-[8px] text-[16px] gap-1 px-[24px] py-[8px] text-white "
                >
                  <span>
                    <PlusIcon />
                  </span>
                  <button className="">Add New Product</button>
                </Link>
                <div className="flex items-center  relative">
                  <input
                    type="text"
                    placeholder="Search by Product Name..."
                    className="border px-[12px] py-[10px] text-[14px] font-[400] rounded-[8px] w-[400px] focus:outline-none border-[#D0D5DD] border-solid"
                  />
                  <span className="absolute left-[23rem] w-[14.67px] text-[#667085] ">
                    <span>
                      <SearchIcon />
                    </span>
                  </span>
                </div>
              </div>

              <div className="xl:inline-block md:hidden">
                <div className="flex justify-between border border-solid rounded-[8px]   ">
                  <button
                    className="inline-flex justify-between h-[38px] w-[200px] px-2  items-center text-[14px]  text-[#667085]"
                    onClick={toggleDropdown}
                  >
                    Filter Product Status
                    <span className="text-[#D0D5DD]">
                      <BiChevronDown size={20} />
                    </span>
                  </button>
                </div>

                {isOpen && (
                  <div className="dropdown-list absolute bg-white text-black shadow-md rounded-[8px] w-[200px]">
                    <div className="py-1" role="none">
                      <Link
                        href="/"
                        className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                      >
                        Log in
                      </Link>
                      <Link
                        href="/"
                        className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                      >
                        Register
                      </Link>
                    </div>
                  </div>
                )}
              </div>
              <div className="xl:hidden md:block">
              <button className="rounded-[8px] border border-solid p-2 border-[#8D98AF]">
                <FilterIcon />
              </button>
            </div>
            </div>
          </div>

          <section className="p-6">
            <div className="flex flex-col">
              <div className="-my-2 overflow-x-auto sm:-mx-8 ">
                <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                  <div className="overflow-hidden">
                    <table className="min-w-full  divide-gray-200">
                      <thead>
                        <tr>
                          <div className="flex gap-2 items-center">
                            <span className=" rounded-[4px]">
                              <input
                                type="checkbox"
                                className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                              />
                            </span>
                            <th
                              scope="col"
                              className="py-3 text-left font-bold text-[14px] text-[#8D98AF] tracking-wider"
                            >
                              Product Name
                            </th>

                            <span>
                              <DropIcon />
                            </span>
                          </div>
                          <th
                            scope="col"
                            className="px-6 py-3 text-left  text-xs font-medium text-gray-500  tracking-wider"
                          >
                            <div className="flex gap-2 items-center">
                              <h1 className="text-[14px] text-[#8D98AF] font-bold">
                                Stock
                              </h1>
                              <span>
                                <DropIcon />
                              </span>
                            </div>
                          </th>
                          <th
                            scope="col"
                            className="px-6 py-3 text-left text-xs font-medium text-gray-500 tracking-wider"
                          >
                            <div className="flex gap-2 items-center">
                              <h1 className="text-[14px] text-[#8D98AF] font-bold">
                                Price
                              </h1>
                              <span>
                                <DropIcon />
                              </span>
                            </div>
                          </th>
                          <th
                            scope="col"
                            className="px-6 py-3 text-left text-xs font-medium text-gray-500  tracking-wider"
                          >
                            <div className="flex gap-2 items-center">
                              <h1 className="text-[14px] text-[#8D98AF] font-bold">
                                Sales Graph
                              </h1>
                              <span>
                                <DropIcon />
                              </span>
                            </div>
                          </th>
                        </tr>
                      </thead>

                      <tbody className="bg-white w-1/3 divide-y  divide-gray-200">
                        <tr className="hover:bg-[#F6F6FF]">
                          <td className=" py-4 w-[440px] whitespace-nowrap">
                            <div className="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div className="flex-shrink-0">
                                <Image
                                  src={Curology}
                                  alt="Curology Male Skin Care"
                                />
                              </div>
                              <div className="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Curology Male Skin Care
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Health & Care
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div className="text-sm text-gray-900">120 pcs</div>
                          </td>
                          <td className="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div className="text-sm text-gray-900">$150</div>
                          </td>
                          <td className="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector1} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +4.4%
                              </p>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td className=" py-4 w-[440px] whitespace-nowrap">
                            <div className="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div className="flex-shrink-0">
                                <Image src={Xbox} alt="Xbox Series X 2021" />
                              </div>
                              <div className="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Xbox Series X 2021
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div className="text-sm text-gray-900">19 pcs</div>
                          </td>
                          <td className="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div className="text-sm text-gray-900">$899</div>
                          </td>
                          <td className="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector3} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -5.5%
                              </p>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td className=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Smartwatch}
                                  alt="Garmin Smartwatch"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Garmin Smartwatch
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">180 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$650</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector9} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -2.3%
                              </p>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3 hover:fill-[#443DF6]">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image src={Vans} alt="Vans Oldskool Classic" />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Vans Oldskool Classic
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Fashion
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">90 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$199</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector1} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +7.6%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Xboxseries}
                                  alt="Xbox Series X Controller - White"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Xbox Series X Controller - White
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">77 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$80</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector4} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +3.2%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image src={Ipad} alt="iPad Pro m1 2021" />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    iPad Pro m1 2021
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">300 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$1099</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector3} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -4.2%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Lovecorn}
                                  alt="Love Corn - Sea Salt Flavour"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Love Corn - Sea Salt Flavour
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Food
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">220 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$10</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector9} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -0.7%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Logittex}
                                  alt="Logitech MX Master 3"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Logitech MX Master 3
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">50 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$120</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector1} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +1.2%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Chair}
                                  alt="Tall Chair Wood Materials"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Tall Chair Wood Materials
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Furniture
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">81 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$100</div>
                          </td>
                          <td className="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector9} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -2.1%
                              </p>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td className=" py-4  whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Leather}
                                  alt="Leather Jacket - Black"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Leather Jacket - Black
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Fashion
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-[#000000]">0 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$88</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector4} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +4.1%
                              </p>
                            </div>
                          </td>
                          <td className="px-6  py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon/>
                            </div>
                          </td>
                        </tr>
                        <hr className="w-[400%]" />
                      </tbody>
                    </table>

                    <div className="flex items-center justify-between">
                      <div className="inline-block  mt-8">
                        <div className="flex justify-between border border-solid rounded-[8px]   ">
                          <button
                            className="inline-flex justify-between h-[38px] w-[200px] px-2  items-center text-[14px]  text-[#667085]"
                            onClick={toggleDropdown}
                          >
                            10 List Per Page
                            <span className="text-[#D0D5DD]">
                              <BiChevronDown size={20} />
                            </span>
                          </button>
                        </div>

                        {isOpen && (
                          <div className="dropdown-list absolute bg-white text-black shadow-md rounded-[8px] w-[200px]">
                            <div className="py-1" role="none">
                              <Link
                                href="/"
                                className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                role="menuitem"
                              >
                                Log in
                              </Link>
                              <Link
                                href="/"
                                className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                              >
                                Register
                              </Link>
                            </div>
                          </div>
                        )}
                      </div>
                      <div className="flex gap-2 mt-8 items-center">
                        <div
                          className="border boder-solid rounded-[8px] px-[13px] py-[10px] 
                        w-[38px] h-[38px] "
                        >
                          <PreviousIcon />
                        </div>
                        <div
                          className="border border-solid rounded-[8px] w-[60px] py-[8px] 
                        px-[25px] h-[38px] text-[14px]"
                        >
                          1
                        </div>
                        <div
                          className="border boder-solid rounded-[8px] px-[13px] py-[10px] 
                        w-[38px] h-[38px]"
                        >
                          <NextIcon />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* mobile design */}
        <div className="md:hidden mx-4 block">
          <div className=" flex justify-between">
            <div className="flex -ml-6 items-center gap-2">
              <h1 className="text-[18px]">Product List</h1>
              <span>
                <BiChevronDown size={20} />
              </span>
            </div>
            <div className="flex items-center gap-4">
              <span>
                <SearchIcon className="w-[22px] h-[22px]" />
              </span>
              <span>
                <NotificationIcon />
              </span>
            </div>
          </div>

          <div className="flex items-center mt-6 justify-between">
            <div className="-ml-6">
              <Link
                href="/newproduct"
                className="flex items-center bg-[#443DF6] rounded-[8px] text-[16px] h-[38px] gap-1 px-[60px] py-[8px] text-white "
              >
                <span>
                  <PlusIcon />
                </span>
                <button className="">Add New Product</button>
              </Link>
            </div>

            <div>
              <button className="rounded-[8px] border border-solid p-2 border-[#8D98AF]">
                <FilterIcon />
              </button>
            </div>
          </div>

          <div className="mt-6 -ml-4">
            <div className="flex gap-2 items-center">
              <th
                scope="col"
                className="py-3 text-left font-bold text-[14px] text-[#8D98AF] tracking-wider"
              >
                Product Name
              </th>

              <span>
                <DropIcon />
              </span>
            </div>

            <div>
              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div className="flex-shrink-0">
                    <Image src={Curology} alt="Curology Male Skin Care" />
                  </div>
                  <div className="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Curology Male Skin Care
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">
                        Health & Care
                      </p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div className="flex-shrink-0">
                    <Image src={Xbox} alt="Xbox Series X 2021" />
                  </div>
                  <div className="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Xbox Series X 2021
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Electronics</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Smartwatch} alt="Garmin Smartwatch" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Garmin Smartwatch
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Electronics</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Vans} alt="Vans Oldskool Classic" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Vans Oldskool Classic
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Fashion</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image
                      src={Xboxseries}
                      alt="Xbox Series X Controller - White"
                    />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Xbox Series X Controller - White
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Electronics</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Ipad} alt="iPad Pro m1 2021" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        iPad Pro m1 2021
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Electronics</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Lovecorn} alt="Love Corn - Sea Salt Flavour" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Love Corn - Sea Salt Flavour
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Food</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Logittex} alt="Logitech MX Master 3" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Logitech MX Master 3
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Electronics</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Chair} alt="Tall Chair Wood Materials" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Tall Chair Wood Materials
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Furniture</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />

              <div className="flex mt-3 justify-between">
                <div className="flex gap-3 items-center">
                  <div class="flex-shrink-0">
                    <Image src={Leather} alt="Leather Jacket - Black" />
                  </div>
                  <div class="">
                    <div className="leading-[0.95rem]">
                      <h1 className="text-[14px] font-bold">
                        Leather Jacket - Black
                      </h1>
                      <p className="text-[12px] text-[#8D98AF]">Fashion</p>
                    </div>
                  </div>
                </div>
                <span>
                  <NextIcon />
                </span>
              </div>
              <hr className="w-full -ml-3 mb-4 mt-3" />
            </div>
          </div>

          <div className="flex gap-2 mb-[4rem] -ml-8 justify-center mt-1 items-center">
            <div
              className="border boder-solid rounded-[8px] px-[13px] py-[10px] 
              w-[38px] h-[38px] "
            >
              <PreviousIcon />
            </div>
            <div
              className="border border-solid rounded-[8px] w-[60px] py-[8px] 
              px-[25px] h-[38px] text-[14px]"
            >
              1
            </div>
            <div
              className="border boder-solid rounded-[8px] px-[13px] py-[10px] 
              w-[38px] h-[38px]"
            >
              <NextIcon />
            </div>
          </div>

          <div className="mx-2 py-3 px-4 rounded-[12px] w-full bg-white shadow-md fixed bottom-0 left-[3.2rem] -ml-6 h-[56px]">
            <div className="flex gap-[3rem] 425:gap-[4.3rem] items-center">
              <div>
                <span className="text-center ">
                  <svg
                    width="20"
                    height="20"
                    viewBox="0 0 20 20"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className="ml-1"
                  >
                    <path
                      d="M15.3489 8.16933C15.595 7.85344 15.5369 7.39843 15.219 7.15306C14.9012 6.90575 14.4458 6.96468 14.1996 7.28251L11.809 10.3574L9.07641 8.21763C8.92428 8.09688 8.73241 8.04278 8.53667 8.0679C8.3448 8.09205 8.16941 8.19155 8.05119 8.34515L5.15091 12.103C4.90575 12.4199 4.96583 12.8749 5.28367 13.1193C5.41545 13.2198 5.57147 13.2691 5.72651 13.2691C5.94454 13.2691 6.15966 13.1715 6.30308 12.986L8.75567 9.8087L11.4864 11.9475C11.6395 12.0663 11.8313 12.1224 12.0251 12.0963C12.217 12.0731 12.3914 11.9736 12.5097 11.821L15.3489 8.16933Z"
                      fill="#9EA9C1"
                    />
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M20 5.89302C20 2.36837 17.733 0 14.3591 0H5.64093C2.26698 0 0 2.36837 0 5.89302V14.107C0 17.6316 2.26698 20 5.64093 20H14.3591C17.733 20 20 17.6316 20 14.107V5.89302ZM5.64093 1.39535H14.3591C16.9386 1.39535 18.6047 3.16 18.6047 5.89302V14.107C18.6047 16.84 16.9386 18.6047 14.3591 18.6047H5.64093C3.06233 18.6047 1.39535 16.84 1.39535 14.107V5.89302C1.39535 3.16 3.06233 1.39535 5.64093 1.39535Z"
                      fill="#9EA9C1"
                    />
                  </svg>
                </span>
                <p className="text-[#9EA9C1] text-[12px] ">Sales</p>
              </div>

              <div>
                <span>
                  <svg
                    width="22"
                    height="22"
                    viewBox="0 0 22 22"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className="ml-2"
                  >
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M4.79487 12.4103C9.38554 12.4103 9.58974 13.9672 9.58974 17.2051C9.58974 18.8275 9.58974 19.9816 8.90831 20.8267C8.12421 21.8003 6.69703 22 4.79487 22C2.89272 22 1.46554 21.8003 0.681436 20.8267C0 19.9816 0 18.8286 0 17.2333L0.846154 17.2051H0C0 13.9672 0.204205 12.4103 4.79487 12.4103ZM17.2051 12.4103C21.7958 12.4103 22 13.9672 22 17.2051C22 18.8275 22 19.9816 21.3186 20.8267C20.5345 21.8003 19.1073 22 17.2051 22C15.303 22 13.8758 21.8003 13.0917 20.8267C12.4103 19.9816 12.4103 18.8286 12.4103 17.2333L13.2564 17.2051H12.4103C12.4103 13.9672 12.6145 12.4103 17.2051 12.4103ZM5.02746 14.1031L4.79487 14.1026C1.85141 14.1026 1.70047 14.3138 1.69273 16.7844L1.6932 17.7469C1.69855 18.7295 1.73599 19.4393 1.99805 19.7662C2.29703 20.1362 3.18492 20.3077 4.79487 20.3077C6.40482 20.3077 7.29272 20.1351 7.59169 19.765C7.89744 19.3848 7.89744 18.4823 7.89744 17.2322C7.89744 14.4115 7.89744 14.1163 5.02746 14.1031ZM17.4377 14.1031L17.2051 14.1026C14.2617 14.1026 14.1107 14.3138 14.103 16.7844L14.1035 17.7469C14.1088 18.7295 14.1462 19.4393 14.4083 19.7662C14.7073 20.1362 15.5952 20.3077 17.2051 20.3077C18.8151 20.3077 19.703 20.1351 20.0019 19.765C20.3077 19.3848 20.3077 18.4823 20.3077 17.2322C20.3077 14.4115 20.3077 14.1163 17.4377 14.1031ZM4.79487 0C9.38554 0 9.58974 1.55692 9.58974 4.79487C9.58974 6.41723 9.58974 7.57138 8.90831 8.41641C8.12421 9.39005 6.69703 9.58974 4.79487 9.58974C2.89272 9.58974 1.46554 9.39005 0.681436 8.41641C0 7.57138 0 6.41836 0 4.82308L0.846154 4.79487H0C0 1.55692 0.204205 0 4.79487 0ZM17.2051 0C21.7958 0 22 1.55692 22 4.79487C22 6.41723 22 7.57138 21.3186 8.41641C20.5345 9.39005 19.1073 9.58974 17.2051 9.58974C15.303 9.58974 13.8758 9.39005 13.0917 8.41641C12.4103 7.57138 12.4103 6.41836 12.4103 4.82308L13.2564 4.79487H12.4103C12.4103 1.55692 12.6145 0 17.2051 0ZM5.02746 1.69281L4.79487 1.69231C1.85141 1.69231 1.70047 1.90352 1.69273 4.37411L1.6932 5.33661C1.69855 6.31924 1.73599 7.02904 1.99805 7.3559C2.29703 7.72595 3.18492 7.89744 4.79487 7.89744C6.40482 7.89744 7.29272 7.72482 7.59169 7.35477C7.89744 6.97456 7.89744 6.072 7.89744 4.82195C7.89744 2.0012 7.89744 1.70609 5.02746 1.69281ZM17.4377 1.69281L17.2051 1.69231C14.2617 1.69231 14.1107 1.90352 14.103 4.37411L14.1035 5.33661C14.1088 6.31924 14.1462 7.02904 14.4083 7.3559C14.7073 7.72595 15.5952 7.89744 17.2051 7.89744C18.8151 7.89744 19.703 7.72482 20.0019 7.35477C20.3077 6.97456 20.3077 6.072 20.3077 4.82195C20.3077 2.0012 20.3077 1.70609 17.4377 1.69281Z"
                      fill="black"
                    />
                  </svg>
                </span>
                <p className="text-black text-[12px] ">Product</p>
              </div>

              <div>
                <span>
                  <svg
                    width="22"
                    height="20"
                    viewBox="0 0 22 20"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className="ml-1"
                  >
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M16.0232 0C19.4306 0 22 2.78667 22 6.48205V13.5262C22 15.4174 21.3328 17.1262 20.1203 18.3385C19.0326 19.4246 17.6215 20 16.0395 20H5.9574C4.37851 20 2.96847 19.4256 1.87972 18.3385C0.667163 17.1262 0 15.4174 0 13.5262V6.48205C0 2.78667 2.5694 0 5.97684 0H16.0232ZM16.0232 1.53846H5.97684C3.40335 1.53846 1.53488 3.61744 1.53488 6.48205V13.5262C1.53488 15.0062 2.04242 16.3282 2.96335 17.2482C3.7574 18.0431 4.79395 18.4615 5.96047 18.4615H16.0232C16.0252 18.4595 16.0334 18.4615 16.0395 18.4615C17.2071 18.4615 18.2426 18.0431 19.0367 17.2482C19.9586 16.3282 20.4651 15.0062 20.4651 13.5262V6.48205C20.4651 3.61744 18.5967 1.53846 16.0232 1.53846ZM17.6358 6.28595C17.9029 6.61518 17.8527 7.09928 17.5243 7.368L12.9769 11.0726C12.4019 11.5301 11.7142 11.7588 11.0276 11.7588C10.3431 11.7588 9.66056 11.5321 9.08958 11.0788L4.50028 7.37005C4.16977 7.10338 4.1186 6.61826 4.38363 6.288C4.6507 5.95877 5.13367 5.90646 5.46316 6.1721L10.0484 9.87672C10.6245 10.3342 11.4359 10.3342 12.0161 9.87262L16.5553 6.17415C16.8847 5.90441 17.3677 5.95569 17.6358 6.28595Z"
                      fill="#9EA9C1"
                    />
                  </svg>
                </span>
                <p className="text-[#9EA9C1] text-[12px] ">Email</p>
              </div>

              <div>
                <span>
                  <MoreIcon className="w-[25px]" />
                </span>
                <p className="text-[#9EA9C1] text-[12px] ">More</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
