import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import {
  PlusIcon,
  SearchIcon,
  DropIcon,
  EditIcon,
  DeleteIcon,
  CopyIcon,
  PreviousIcon,
  NextIcon,
} from "@/components/Icon";
import { BiChevronDown } from "react-icons/bi";
import { productlist } from "@/data";
import Image from "next/image";
import Curology from "/public/assests/skincare.png";
import Xbox from "/public/assests/xboxseries.png";
import Smartwatch from "/public/assests/smartwatch.png";
import Vans from "/public/assests/vans classic.png";
import Xboxseries from "/public/assests/xboxseriescontroller.png";
import Ipad from "/public/assests/ipadpro.png";
import Lovecorn from "/public/assests/lovecorn.png";
import Logittex from "/public/assests/logitex.png";
import Chair from "/public/assests/tallchair.png";
import Leather from "/public/assests/leatherjacket.png";
import Vector1 from "/public/assests/Vector 18.svg";
import Vector3 from "/public/assests/Vector 16.svg";
import Vector4 from "/public/assests/Vector 17.svg";
import Vector9 from "/public/assests/Vector 19.svg";

export default function Home() {
  function toggleDropdown() {
    setIsOpen(!isOpen);
  }
  const [isOpen, setIsOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Kitagrow</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="mt-4 w-full ">
        <div className="border-t  border-l border-none shadow-md rounded-[40px_0_0_0] min-h-[1032px] ">
          <div className="p-6">
            <h1 className="text-[32px] font-bold">Product List</h1>
            <p className="text-[16px] text-[#667085]">
              Manage & Add Product list on your marketplace
            </p>
            <div className="flex mt-8 w-auto justify-between">
              <div className="flex gap-2">
                <Link
                  href='/newproduct'
                  className="flex items-center bg-[#443DF6] rounded-[8px] text-[16px] gap-1 px-[24px] py-[8px] text-white "
                >
                  <span>
                    <PlusIcon />
                  </span>
                  <button className="">Add New Product</button>
                </Link>
                <div className="flex items-center  relative">
                  <input
                    type="text"
                    placeholder="Search by Product Name..."
                    className="border px-[12px] py-[10px] text-[14px] font-[400] rounded-[8px] w-[400px] focus:outline-none border-[#D0D5DD] border-solid"
                  />
                  <span className="absolute left-[23rem] w-[14.67px] text-[#667085] ">
                    <span>
                      <SearchIcon />
                    </span>
                  </span>
                </div>
              </div>

              <div className="inline-block">
                <div className="flex justify-between border border-solid rounded-[8px]   ">
                  <button
                    className="inline-flex justify-between h-[38px] w-[200px] px-2  items-center text-[14px]  text-[#667085]"
                    onClick={toggleDropdown}
                  >
                    Filter Product Status
                    <span className="text-[#D0D5DD]">
                      <BiChevronDown size={20} />
                    </span>
                  </button>
                </div>

                {isOpen && (
                  <div className="dropdown-list absolute bg-white text-black shadow-md rounded-[8px] w-[200px]">
                    <div className="py-1" role="none">
                      <Link
                        href="/"
                        className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                        role="menuitem"
                      >
                        Log in
                      </Link>
                      <Link
                        href="/"
                        className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                      >
                        Register
                      </Link>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          <section className="p-6">
            <div className="flex flex-col">
              <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                  <div class="overflow-hidden">
                    <table class="min-w-full  divide-gray-200">
                      <thead>
                        <tr>
                          <div className="flex gap-2 items-center">
                            <span className=" rounded-[4px]">
                              <input
                                type="checkbox"
                                className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                              />
                            </span>
                            <th
                              scope="col"
                              class="py-3 text-left font-bold text-[14px] text-[#8D98AF] tracking-wider"
                            >
                              Product Name
                            </th>

                            <span>
                              <DropIcon />
                            </span>
                          </div>
                          <th
                            scope="col"
                            class="px-6 py-3 text-left  text-xs font-medium text-gray-500  tracking-wider"
                          >
                            <div className="flex gap-2 items-center">
                              <h1 className="text-[14px] text-[#8D98AF] font-bold">
                                Stock
                              </h1>
                              <span>
                                <DropIcon />
                              </span>
                            </div>
                          </th>
                          <th
                            scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 tracking-wider"
                          >
                            <div className="flex gap-2 items-center">
                              <h1 className="text-[14px] text-[#8D98AF] font-bold">
                                Price
                              </h1>
                              <span>
                                <DropIcon />
                              </span>
                            </div>
                          </th>
                          <th
                            scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500  tracking-wider"
                          >
                            <div className="flex gap-2 items-center">
                              <h1 className="text-[14px] text-[#8D98AF] font-bold">
                                Sales Graph
                              </h1>
                              <span>
                                <DropIcon />
                              </span>
                            </div>
                          </th>
                        </tr>
                      </thead>

                      <tbody class="bg-white w-1/3 divide-y  divide-gray-200">
                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Curology}
                                  alt="Curology Male Skin Care"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Curology Male Skin Care
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Health & Care
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">120 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$150</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector1} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +4.4%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image src={Xbox} alt="Xbox Series X 2021" />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Xbox Series X 2021
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">19 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$899</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector3} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -5.5%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Smartwatch}
                                  alt="Garmin Smartwatch"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Garmin Smartwatch
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">180 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$650</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector9} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -2.3%
                              </p>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3 hover:fill-[#443DF6]">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image src={Vans} alt="Vans Oldskool Classic" />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Vans Oldskool Classic
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Fashion
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">90 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$199</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector1} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +7.6%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Xboxseries}
                                  alt="Xbox Series X Controller - White"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Xbox Series X Controller - White
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td className="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">77 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$80</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector4} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +3.2%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image src={Ipad} alt="iPad Pro m1 2021" />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    iPad Pro m1 2021
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">300 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$1099</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector3} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -4.2%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Lovecorn}
                                  alt="Love Corn - Sea Salt Flavour"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Love Corn - Sea Salt Flavour
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Food
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">220 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$10</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector9} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -0.7%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Logittex}
                                  alt="Logitech MX Master 3"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Logitech MX Master 3
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Electronics
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">50 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$120</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector1} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +1.2%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Chair}
                                  alt="Tall Chair Wood Materials"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Tall Chair Wood Materials
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Furniture
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">81 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$100</div>
                          </td>
                          <td className="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector9} />
                              <p className="bg-[#FEF3F2] px-2 py-1 text-[12px] rounded-[20px] text-[#912018]">
                                -2.1%
                              </p>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>

                        <tr className="hover:bg-[#F6F6FF]">
                          <td class=" py-4 w-[440px] whitespace-nowrap">
                            <div class="flex gap-3 items-center">
                              <span className="w-[12px] rounded-[4px]">
                                <input
                                  type="checkbox"
                                  className=" appearance-none border border-solid rounded-[4px] checked:bg-blue-600 h-[12px] w-[12px] shadow-sm border-[#D0D5DD] "
                                />
                              </span>
                              <div class="flex-shrink-0">
                                <Image
                                  src={Leather}
                                  alt="Leather Jacket - Black"
                                />
                              </div>
                              <div class="">
                                <div className="leading-[0.95rem]">
                                  <h1 className="text-[14px] font-bold">
                                    Leather Jacket - Black
                                  </h1>
                                  <p className="text-[12px] text-[#8D98AF]">
                                    Fashion
                                  </p>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-[#000000]">0 pcs</div>
                          </td>
                          <td class="px-6 py-4 w-[150px] whitespace-nowrap">
                            <div class="text-sm text-gray-900">$88</div>
                          </td>
                          <td class="px-6 py-4 w-[220px] whitespace-nowrap text-sm text-gray-500">
                            <div className="flex gap-4">
                              <Image alt="graph" src={Vector4} />
                              <p className="bg-[#ECFDF3] px-2 py-1 text-[12px] rounded-[20px] text-[#027A48]">
                                +4.1%
                              </p>
                            </div>
                          </td>
                          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <div className="flex gap-3">
                              <CopyIcon />
                              <EditIcon />
                              <DeleteIcon />
                            </div>
                          </td>
                        </tr>
                        <hr className="w-[400%]" />
                      </tbody>
                    </table>

                    

                    <div className="flex items-center justify-between">
                      <div className="inline-block  mt-8">
                        <div className="flex justify-between border border-solid rounded-[8px]   ">
                          <button
                            className="inline-flex justify-between h-[38px] w-[200px] px-2  items-center text-[14px]  text-[#667085]"
                            onClick={toggleDropdown}
                          >
                            10 List Per Page
                            <span className="text-[#D0D5DD]">
                              <BiChevronDown size={20} />
                            </span>
                          </button>
                        </div>

                        {isOpen && (
                          <div className="dropdown-list absolute bg-white text-black shadow-md rounded-[8px] w-[200px]">
                            <div className="py-1" role="none">
                              <Link
                                href="/"
                                className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                role="menuitem"
                              >
                                Log in
                              </Link>
                              <Link
                                href="/"
                                className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                              >
                                Register
                              </Link>
                            </div>
                          </div>
                        )}

                      
                      </div>
                      <div className="flex gap-2 mt-8 items-center">
                        <div className="border boder-solid rounded-[8px] px-[13px] py-[10px] 
                        w-[38px] h-[38px] "><PreviousIcon/></div>
                        <div className="border border-solid rounded-[8px] w-[60px] py-[8px] 
                        px-[25px] h-[38px] text-[14px]">1</div>
                        <div className="border boder-solid rounded-[8px] px-[13px] py-[10px] 
                        w-[38px] h-[38px]"><NextIcon/></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
